language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t julbarg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julbarg/docker-react npm run test